name: Check and Delete File 
 
on:
  push:
    branches: [ main ]  # 触发分支，按需修改 
  schedule:
    - cron: '0 0 * * *'  # 可选：每天定时检查 
 
jobs:
  check-and-delete:
    runs-on: ubuntu-latest 
    permissions:
      contents: write  # 需要写入权限以提交更改 
 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录 
 
      - name: Check and delete file 
        run: |
          if [ -f "aaa.m3u" ]; then 
            git rm aaa.m3u 
            git config --global user.name  "github-actions[bot]"
            git config --global user.email  "github-actions[bot]@users.noreply.github.com" 
            git commit -m "Automatically delete aaa.mu3" 
            git push origin HEAD:${{ github.ref  }}
          else 
            echo "File aaa.m3u does not exist."
          fi 
