name: Delete Specific File 
on:
  workflow_dispatch:  # 允许手动触发 

jobs:
  delete-file:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4  # 检出代码到工作环境 

      - name: Delete file 
        run: |
          git rm aaa.m3u  # 删除指定文件 
          git config --global user.name  "github-actions"
          git config --global user.email  "actions@github.com" 
          git commit -m "Remove aaa.m3u via GitHub Actions"
          git push origin main  # 分支名根据实际情况调整 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用默认权限令牌 
