name: Fetch M3U Files 
on:
  workflow_dispatch: # 支持手动触发 
  schedule:
    - cron: '0 */6 * * *' # 每6小时自动执行（可选定时任务）

jobs:
  fetch-files:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Read list and download 
        run: |
          # 读取 liebiao.txt  内容（假设每行一个 URL）
          URL1=$(sed -n '1p' cheshi/liebiao.txt) 
          URL2=$(sed -n '2p' cheshi/liebiao.txt) 
          
          # 下载文件并保存 
          curl -o cheshi/aaa1.m3u "$URL1"
          curl -o cheshi/aaa2.m3u "$URL2"

      - name: Commit and push 
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email  "actions@github.com" 
          git add cheshi/aaa*.m3u
          git commit -m "Auto-update m3u files"
          git push 
