name: Fetch M3U Files 
on:
  workflow_dispatch: # 支持手动触发 
  schedule:
    - cron: '0 0 * * *' # 可选定时任务（每天0点执行）

jobs:
  fetch-files:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Read URLs and Download 
        run: |
          i=1 
          while read url; do 
            curl -s -o "bbb$i.m3u" "$url"
            ((i++))
          done < liebiao.txt  

      - name: Commit changes 
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email  "actions@github.com" 
          git add bbb*.m3u
          git commit -m "Auto-update M3U files"
          git push 
