name: Process M3U Files 
on:
  workflow_dispatch: # 手动触发 
  push:
    paths:
      - 'liebiao.txt'  # 当 liebiao.txt  变更时自动触发 
 
jobs:
  process-m3u:
    runs-on: ubuntu-latest 
    steps:
      # 步骤1：检出代码 
      - name: Checkout repository 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      # 步骤2：删除旧文件 
      - name: Remove existing bbb.m3u 
        run: |
          if [ -f "bbb.m3u" ]; then 
            git rm bbb.m3u 
            git commit -m "Remove old bbb.m3u"
          fi 
 
      # 步骤3：下载并合并文件 
      - name: Download and merge M3U 
        run: |
          # 读取 URL 列表 
          while IFS= read -r url; do 
            # 下载文件并追加内容 
            curl -s "$url" >> temp.m3u 
          done < liebiao.txt  
 
          # 过滤 updateTime* 行并去重 
          grep -v "updateTime" temp.m3u | sort -u > bbb.m3u 
          rm temp.m3u 
 
      # 步骤4：提交变更 
      - name: Commit changes 
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email  "actions@github.com" 
          git add bbb.m3u 
          git commit -m "Update merged M3U file" || echo "No changes to commit"
          git push 
