name: Process M3U Files 
 
on:
  workflow_dispatch:
 
jobs:
  process-m3u:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4
 
      - name: Delete existing bbb.m3u 
        run: |
          if [ -f "cheshi/bbb.m3u" ]; then 
            rm cheshi/bbb.m3u 
            echo "Deleted existing bbb.m3u"
          fi 
 
      - name: Fetch URLs from liebiao.txt  
        id: fetch-urls
        run: |
          URLS=$(cat cheshi/liebiao.txt  | tr '\n' ' ')
          echo "urls=$URLS" >> $GITHUB_OUTPUT 
 
      - name: Download and merge M3U files 
        run: |
          mkdir -p temp 
          for url in ${{ steps.fetch-urls.outputs.urls  }}; do 
            wget -q "$url" -O "temp/$(basename $url)"
            cat "temp/$(basename $url)" >> cheshi/bbb.m3u 
          done 
          rm -rf temp 
 
      - name: Filter updateTime lines 
        run: |
          sed -i '/updateTime*/d' cheshi/bbb.m3u 
 
      - name: Commit changes 
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main 
          commit_message: "[Automated] Update merged M3U file"
          file_pattern: cheshi/bbb.m3u 
