name: M3U2 Files 
 
on:
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: '5 14 * * *' # 每天UTC时间0点自动运行[1]()[8]()
 
jobs:
  process-m3u:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写入权限以提交更改
 
    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
          fetch-depth: 0  # 拉取完整历史记录

    - name: Check and delete file 
      run: |
        if [ -f "ipv4直播源2.m3u" ]; then 
          git rm ipv4直播源2.m3u 
          git config --global user.name  "github-actions[bot]"
          git config --global user.email  "github-actions[bot]@users.noreply.github.com" 
          git commit -m "Automatically delete ipv4直播源2.mu3" 
          git push origin HEAD:${{ github.ref  }}
        else 
          echo "File ipv4直播源2.m3u does not exist."
        fi  
 
    - name: Merge and process files 
      run: |
        # 安装必要工具 
        sudo apt-get install -y curl 
 
        # 创建临时目录 
        mkdir -p tmp_m3u 
 
        # 逐行读取liebiao2.txt 并下载文件 
        while IFS= read -r url; do 
          filename=$(basename "$url")
          curl -s "$url" -o "tmp_m3u/${filename}"
        done < liebiao2.txt  
 
        # 合并文件并删除updateTime行
        cat tmp_m3u/*.m3u > ipv4直播源2.m3u 
        sed -i '/updateTime/d' ipv4直播源2.m3u 
 
        # 清理临时文件 
        rm -rf tmp_m3u 
 
    - name: Commit changes 
      run: |
        git config --global user.name  "GitHub Actions"
        git config --global user.email  "actions@github.com" 
        git add ipv4直播源2.m3u 
        git commit -m "Auto update merged M3U file"
        git push 
