name: Merge M3U Files 
 
on: 
  workflow_dispatch: # 支持手动触发 
 
jobs:
  process-m3u:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
 
    - name: Setup environment 
      run: |
        mkdir -p temp 

    - name: Error handling 
      if: ${{ failure() }}
      run: |
         echo "Process failed, check logs"
         exit 1 
 
    - name: Download M3U files 
      run: |
        while read url; do 
          filename=$(basename "$url")
          curl -s "$url" -o "temp/${filename}"
        done < cheshi/liebiao.txt  
 
    - name: Merge and filter 
      run: |
        # 合并文件并删除updateTime行
        cat temp/*.m3u | grep -v "updateTime" > cheshi/bbb.m3u 
        
        # 清理临时文件 
        rm -rf temp 
 
    - name: Commit changes 
      run: |
        git config --global user.name  "GitHub Actions"
        git config --global user.email  "actions@github.com" 
        git add cheshi/bbb.m3u 
        git commit -m "Auto-merged M3U files"
        git push 
