name: Merge M3U Files 
 
on:
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间0点执行 
  workflow_dispatch: # 允许手动触发 
 
jobs:
  merge-m3u:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
 
    - name: Set up Python 
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
 
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip 
        pip install requests 
 
    - name: Run merge script 
      run: |
        cat <<EOF > merge_script.py  
        import os 
        import requests 
        from urllib.parse  import urlparse 
 
        # 读取列表文件 
        with open('liebiao.txt',  'r') as f:
            urls = [line.strip() for line in f if line.strip()] 
 
        merged_content = []
        seen_lines = set()  # 用于去重（可选）
 
        for url in urls:
            try:
                response = requests.get(url) 
                response.raise_for_status() 
                
                # 解析内容并过滤 
                for line in response.text.splitlines(): 
                    line = line.strip() 
                    if '#EXTM3U' in line:  # 跳过文件头
                        continue 
                    if 'updateTime' in line:  # 过滤特定行
                        continue 
                    if line not in seen_lines:  # 去重逻辑（可选）
                        merged_content.append(line) 
                        seen_lines.add(line) 
            except Exception as e:
                print(f"Error processing {url}: {str(e)}")
 
        # 生成最终文件 
        with open('cheshi/bbb.m3u', 'w') as f:
            f.write('#EXTM3U\n') 
            f.write('\n'.join(merged_content)) 
        EOF 
        
        python merge_script.py  
 
    - name: Commit changes 
      run: |
        git config --global user.name  "GitHub Actions"
        git config --global user.email  "actions@github.com" 
        git add cheshi/bbb.m3u 
        git commit -m "Auto update merged m3u file"
        git push 
