name: Merge M3U Files 
 
on:
  push:
    paths:
      - 'liebiao.txt'  # 当liebiao.txt 文件变更时触发 
  workflow_dispatch: # 允许手动触发 
 
jobs:
  merge-m3u:
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v4
 
    - name: Download and process files 
      run: |
        # 下载所有m3u文件 
        while read url; do 
          curl -sL "$url" --output-dir m3u_files -O
        done < liebiao.txt  
 
        # 合并文件并过滤内容 
        cat m3u_files/*.m3u | grep -v 'updateTime*' > cheshi/bbb.m3u 
 
        # 验证生成文件 
        echo "Total lines: $(wc -l bbb.m3u)"
 
    - name: Commit result 
      run: |
        git config --global user.name  "GitHub Actions"
        git config --global user.email  "actions@github.com" 
        git add bbb.m3u 
        git commit -m "Auto update merged m3u file"
        git push 
