name: Sync GitHub to Gitee
 
on:
  push:
    branches:
      - main  # 监听 GitHub 主分支更新 

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4  # 检出代码到 Actions 运行器 
 
      - name: Setup SSH Key 
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.GITEE_SSH_KEY }}  # 使用 GitHub Secrets 存储的 Gitee 私钥 
 
      - name: Add Gitee Remote 
        run: |
          git remote add gitee ssh://git@gitee.com:hzy0613/cheshi/master.git   # 替换为你的 Gitee 仓库地址 
          git fetch gitee  # 获取 Gitee 远程仓库信息 
 
      - name: Push to Gitee Master 
        run: |
          git push gitee main:master  # 将 GitHub 的 main 分支推送到 Gitee 的 master 分支
          git push gitee --follow-tags  # 同步标签（可选）
