name: Sync GitHub to Gitee
on:
  push:
    branches: [main]  # 同步分支（可修改为需要的分支）
 
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
 
      - name: Setup SSH 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitee.com  >> ~/.ssh/known_hosts 
 
      - name: Sync to Gitee
        run: |
          git config --global user.name  "Your Name"
          git remote add gitee $GITEE_REPO_URL
          git push --force gitee HEAD:main  # 强制同步覆盖
