name: Sync Gitee File
on:
  push:
    branches: [main]
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code 
        uses: actions/checkout@v4
      - name: Setup SSH 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh 
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitee.com  >> ~/.ssh/known_hosts 
      - name: Sync specific file 
        run: |
          # 备份原文件（可选）
          cp ipv4直播源.m3u /tmp/
          
          # 克隆Gitee仓库并替换文件 
          git clone git@gitee.com:hzy0613/cheshi.git  /tmp/gitee-repo 
          cd /tmp/gitee-repo 
          git checkout master 
          cp /tmp/ipv4直播源.m3u .
          
          # 提交更改 
          git config user.name  "GitHub Actions"
          git config user.email  "actions@github.com" 
          git add ipv4直播源.m3u 
          git commit -m "Sync from GitHub [skip ci]"
          git push origin master 
