name: Sync to Gitee
on: [push] # 触发条件：代码推送时同步 

jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Mirror to Gitee
        uses: wearerequired/git-mirror-action@master 
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_PRIVATE_KEY }}
        with:
          # 源仓库（GitHub的SSH地址）
          source-repo: "git@github.com: 你的用户名/仓库名.git"
          # 目标仓库（Gitee的SSH地址）
          destination-repo: "git@gitee.com: 你的Gitee用户名/仓库名.git"
