# 通过 Github action， 在仓库的每一次 commit 后自动同步到 Gitee 上
name: sync2gitee
on:
  push:
    branches:
      - main 
jobs:
  repo-sync:
    env:
      SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Configure Git
        run: |
           git config --global --add safe.directory /github/workspace           

      - name: sync github -> gitee
        uses: wearerequired/git-mirror-action@master
        if: env.SSH_PRIVATE_KEY
        with:
          source-repo: "git@github.com:hzy803/cheshi.git"
          destination-repo: "git@gitee.com:Kat-tun远远/cheshi.git"
