name: Sync to Gitee
on:
  push:
    paths:
      - 'ipv4直播源.m3u'  # 仅当此文件变更时触发 
jobs:
  sync:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout GitHub repo 
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git 
        run: |
          git config --global user.name  "GitHub Actions"
          git config --global user.email  "actions@github.com" 

      - name: Add Gitee Remote 
        run: git remote add gitee git@gitee.com:hzy0613/cheshi.git  

      - name: Push to Gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh 
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519 
          chmod 600 ~/.ssh/id_ed25519 
          ssh-keyscan gitee.com  >> ~/.ssh/known_hosts
          git push gitee HEAD:master --force  # 强制推送指定文件 
